language: cpp
os: osx
compiler: clang

addons:
  # To avoid being prompted when ssh'ing into sourceforge.
  ssh_known_hosts:
      # For uploading doxygen.
      - web.sourceforge.net
      # For deleting old doxygen.
      - shell.sourceforge.net
      # For uploading binaries.
      - frs.sourceforge.net

env: 
  global:
    - SWIG_VER=3.0.8
    - ZIPNAME=opensim-moco-${TRAVIS_OS_NAME}_${TRAVIS_BRANCH}_${TRAVIS_PULL_REQUEST_BRANCH}.zip
    - BTYPE=Release
    - NPROC=2
    - DEPLOY=yes
    - DOXY=on
    - WRAP=on
    - OSX_TARGET=10.10
#  matrix:
#    - BTYPE=Release NPROC=2 DEPLOY=yes DOXY=on WRAP=on OSX_TARGET=10.10

jobs:
  include:
    - stage: dependencies
      name: "opensim-core"
      script: bash .github/travis_dependencies.sh opensim-core
      if: commit_message =~ rebuild deps
    - stage: dependencies
      name: "adolc"
      script: bash .github/travis_dependencies.sh adolc
      if: commit_message =~ rebuild deps
    - stage: dependencies
      name: "casadi"
      script: bash .github/travis_dependencies.sh casadi
      if: commit_message =~ rebuild deps
    - stage: dependencies
      name: "eigen"
      script: bash .github/travis_dependencies.sh eigen
      if: commit_message =~ rebuild deps
    - stage: buildtest
      script: bash .github/travis_buildtest.sh

