language: cpp
os: osx
compiler: clang

addons:
  # To avoid being prompted when ssh'ing into sourceforge.
  ssh_known_hosts:
      # For uploading doxygen.
      - web.sourceforge.net
      # For deleting old doxygen.
      - shell.sourceforge.net
      # For uploading binaries.
      - frs.sourceforge.net

env: 
  global:
    - SWIG_VER=3.0.8
    - ZIPNAME=opensim-moco-${TRAVIS_OS_NAME}_${TRAVIS_BRANCH}_${TRAVIS_PULL_REQUEST_BRANCH}.zip
  matrix:
    - BTYPE=Release NPROC=2 DEPLOY=yes DOXY=on WRAP=on OSX_TARGET=10.10

jobs:
  include:
    - stage: dependencies
      script: bash .github/travis_dependencies.sh opensim-core
    - stage: dependencies
      script: bash .github/travis_dependencies.sh adolc
    - stage: dependencies
      script: bash .github/travis_dependencies.sh casadi
    - stage: dependencies
      script: bash .github/travis_dependencies.sh eigen
    - stage: buildtest
      script: bash .github/travis_buildtest.sh
