# Windows testing using Visual Studio.
#
# Syntax for this file:
# http://www.appveyor.com/docs/appveyor-yml

# See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
# command-line options to MSBuild.

os: Visual Studio 2015

platform: x64

shallow_clone: true

# TODO use project feed instead.
#nuget:
#  account_feed: true

cache:
  ## Cache some dependencies.
  # The syntax here is <dir-to-cache> -> <invalidated-when-this-file-changes>
  # If the appveyor.yml script is changed, then the cache is invalidated.
  # https://www.appveyor.com/docs/build-cache/
  # TODO split AddDependency() calls into separate cmake files so we can
  # invalidate these dependencies separately.
  - C:\projects\eigen -> C:\projects\muscollo\dependencies\CMakeLists.txt
  #- C:\projects\muscollo_deps_install\colpack -> C:\projects\muscollo\dependencies\colpack.cmake
  #- C:\projects\muscollo_deps_install\adol-c -> C:\projects\muscollo\dependencies\CMakeLists.txt
  #- C:\projects\muscollo_deps_install\ipopt -> C:\projects\muscollo\dependencies\CMakeLists.txt
  #- C:\projects\muscollo_deps_install\opensim-core -> C:\projects\muscollo\dependencies\opensim-core.cmake

install:
  - cmake --version

  # Install dependencies.
  # We are using superbuild for opensim-core, as that allows us to specify
  # specific commits to use. Also, for some reason, Muscollo couldn't find
  # OpenSim headers when using NuGet.
  # TODO - nuget sources add -name opensim-core --source https://ci.appveyor.com/nuget/opensim-core-kd63opes1em0
  # TODO - nuget install opensim-core -Version 0.0.0 -ExcludeVersion -OutputDirectory C:\

  # https://blogs.msdn.microsoft.com/vcblog/2016/09/19/vcpkg-a-tool-to-acquire-and-build-c-open-source-libraries-on-windows/
  # https://github.com/Microsoft/vcpkg/blob/master/docs/examples/using-sqlite.md
  # https://github.com/appveyor/ci/issues/1076
  #- vcpkg integrate install
  # TODO cache eigen.
  # TODO vcpkg is pretty slow; using superbuild for now.
  #- vcpkg install eigen3:x64-windows

  - mkdir ..\muscollo_deps_build
  - cd ..\muscollo_deps_build
  # /W0 disables warnings. The other CXX flags are copied from CMake's default
  # CMAKE_CXX_FLAGS.
  # https://msdn.microsoft.com/en-us/library/19z1t1wy.aspx
  # - set CXXFLAGS="/W0"
  - cmake ..\muscollo\dependencies -G"Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX="C:\projects\muscollo_deps_install" -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS /W0 /GR /EHsc" -DSUPERBUILD_eigen=OFF -DSUPERBUILD_colpack=OFF -DSUPERBUILD_adolc=OFF -DSUPERBUILD_ipopt=OFF -DSUPERBUILD_opensim-core=OFF

  - dir C:\projects\muscollo_deps_install
  - dir C:\projects\
  - IF EXIST C:\projects\muscollo_deps_install\eigen dir C:\projects\muscollo_deps_install\eigen
  - IF NOT EXIST C:\projects\eigen cmake . -DSUPERBUILD_eigen=ON
  #- IF NOT EXIST C:\projects\muscollo_deps_install\colpack cmake . -DSUPERBUILD_colpack=ON
  #- IF NOT EXIST C:\projects\muscollo_deps_install\adol-c cmake . -DSUPERBUILD_adolc=ON
  #- IF NOT EXIST C:\projects\muscollo_deps_install\ipopt cmake . -DSUPERBUILD_ipopt=ON
  #- IF NOT EXIST C:\projects\muscollo_deps_install\opensim-core echo testing
  #TODO- IF NOT EXIST C:\projects\muscollo_deps_install\opensim-core cmake . -DSUPERBUILD_opensim-core=ON
  # List the values of the CMake variables.
  - cmake . -LAH

  # The dependencies might spew out a lot of warnings that make the log
  # difficult to read.
  - cmake --build . --config RelWithDebInfo -- /maxcpucount:4 /verbosity:quiet

  - IF NOT EXIST C:\projects\eigen cmake -E copy_directory C:\projects\muscollo_deps_install\eigen C:\projects\eigen
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:

  # Install Muscollo.
  - mkdir ..\build
  - cd ..\build
#  # TODO turn warnings into errors: cmake -E env CXXFLAGS="/WX"
#  - cmake ..\muscollo -G"Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX="C:\muscollo" -DADOLC_DIR="..\muscollo_deps_install\adol-c" -DIPOPT_DIR="..\muscollo_deps_install\ipopt" -DCMAKE_PREFIX_PATH="C:\projects\muscollo_deps_install\colpack;C:\projects\muscollo_deps_install\opensim-core"
#  #-DCMAKE_TOOLCHAIN_FILE="C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
#  - cmake --build . --config RelWithDebInfo -- /maxcpucount:4

test_script:
  #- ctest --build-config RelWithDebInfo --parallel 4 --output-on-failure
  - echo TODO
  #- cmake --build . --config RelWithDebInfo --target install -- /verbosity:quiet

#after_test:
#  - cd %APPVEYOR_BUILD_FOLDER%
#  # TODO consider using plain ZIP artifacts:
#  # https://www.appveyor.com/docs/packaging-artifacts/
#  ## On master branch, create NuGet package for OpenSim.
#  # Detect if we are on the master branch.
#  # TODO change appveyor to master branch.
#  - IF %APPVEYOR_REPO_BRANCH% EQU appveyor IF NOT DEFINED APPVEYOR_PULL_REQUEST_NUMBER SET DISTR=TRUE
#  - IF DEFINED DISTR 7z a C:\opensim-muscollo.zip C:\muscollo
#  - IF DEFINED DISTR appveyor PushArtifact C:\opensim-muscollo.zip
#  # The published binaries can be downloaded from this link: https://ci.appveyor.com/api/projects/opensim-org/muscollo/artifacts/opensim-muscollo.zip
#  # Create and upload NuGet package.
#  #- IF DEFINED DISTR nuget pack .github/opensim-muscollo.nuspec -BasePath C:\muscollo
#  #- IF DEFINED DISTR appveyor PushArtifact opensim-muscollo.0.0.0.nupkg
