# From: https://github.com/shuhaoliu/docker-clion-dev/blob/master/docker-compose.yml

version: '3'

services:
  gdbserver:
    build: .
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    container_name: opensim-moco-dev
    ports:
      - "7776:22"
      - "7777:7777"
    volumes:
      - ../../dependencies:/moco_dependencies
