name: Linux CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      env:
        DEP_BUILD_DIR: $HOME/build_deps
        DEP_INSTALL_DIR: $HOME/opensim_dependencies_install
        BTYPE: Release
      run: |
        REPO=$(pwd)
        echo $DEP_BUILD_DIR
        mkdir $DEP_BUILD_DIR && cd $DEP_BUILD_DIR
        cmake $REPO/dependencies -DCMAKE_INSTALL_PREFIX=$DEP_INSTALL_DIR -DCMAKE_BUILD_TYPE=$BTYPE
        make --jobs 4
