name: Linux CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      env:
        DEP_BUILD_DIR: /home/runner/work/build_deps
        DEP_INSTALL_DIR: /home/runner/work/opensim_dependencies_install
        BUILD_DIR: /home/runner/work/build
        INSTALL_DIR: /home/runner/work/opensim-core-install
        BTYPE: Release
      run: |
        REPO=$(pwd)
        mkdir $DEP_BUILD_DIR && cd $DEP_BUILD_DIR
        cmake $REPO/dependencies -DCMAKE_INSTALL_PREFIX=$DEP_INSTALL_DIR -DCMAKE_BUILD_TYPE=$BTYPE
        make --jobs 4
        mkdir $BUILD_DIR && cd $INSTALL_DIR
        OSIM_CMAKE_ARGS=($BUILD_DIR -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR -DCMAKE_BUILD_TYPE=$BTYPE)
        printf '%s\n' "${OSIM_CMAKE_ARGS[@]}" 
        cmake "${OSIM_CMAKE_ARGS[@]}"
        make --jobs 4
        ctest --jobs 4
        make install
        
      
