name: Windows

# TODO: build master branch after PRs are merged.
# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on: pull_request
    
jobs:
  windows:
    name: Windows

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Doxygen
      # choco install doxygen.portable # <-- too unreliable.
      run: |
        (New-Object System.Net.WebClient).DownloadFile("https://sourceforge.net/projects/myosin/files/doxygen-1.8.14.windows.x64.bin.zip/download", "doxygen.zip")
        ls
        7z x doxygen.zip -o~/doxygen

    - name: Install NumPy 
      run: python -m pip install numpy
 
    - name: Install SWIG
      run: choco install swig --version 3.0.12 --yes --limit-output 
 
    - name: Update submodules
      run: git submodule update --init

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v1
      with:
        path: ~/moco_dependencies_install
        # TODO: avoid having to copy over the opensim-core commit hash.
        key: ${{ runner.os }}-dependencies-${{ hashFiles('dependencies/*') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-
 
    - name: Build dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        echo $env:GITHUB_WORKSPACE\\build_deps
        mkdir $env:GITHUB_WORKSPACE\\build_deps
        chdir $env:GITHUB_WORKSPACE\\build_deps
        # TODO: Ignore warnings in dependencies.
        # /W0 disables warnings. The other flags are copied from CMake's
        # default CMAKE_CXX_FLAGS.
        # https://msdn.microsoft.com/en-us/library/19z1t1wy.aspx
        $env:CXXFLAGS = "/W0"
        cmake $env:GITHUB_WORKSPACE/dependencies -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=~/moco_dependencies_install -DOPENSIM_JAVA_WRAPPING=on -DOPENSIM_PYTHON_WRAPPING=on
        $env:CXXFLAGS = ""
        cmake . -LAH
        cmake --build . --config Release -- /maxcpucount:4 

    - name: Build Moco
      run: |
        mkdir $env:GITHUB_WORKSPACE\\build 
        chdir $env:GITHUB_WORKSPACE\\build
        # TODO: Can remove /WX when we use that in CMakeLists.txt.
        $env:CXXFLAGS = "/WX"
        cmake $env:GITHUB_WORKSPACE -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=~/opensim-core-install -DMOCO_DEPENDENCIES_DIR=~/moco_dependencies_install -DBUILD_JAVA_WRAPPING=on -DBUILD_PYTHON_WRAPPING=on -DDOXYGEN_EXECUTABLE=~/doxygen
        $env:CXXFLAGS = ""
        echo 'DEBUG3'
        cmake . -LAH
        echo 'DEBUG4'
        cmake --build . --config Release -- /maxcpucount:4 /verbosity:minimal

        $env:match = cmake -L . | Select-String -Pattern MOCO_FULL_VERSION
        $env:VERSION = $env:match.split('=')[1]
        $env:VERSION

    - name: Test Moco
      run: |
        chdir $env:GITHUB_WORKSPACE\\build
        ctest --parallel 4 --output-on-failure --build-config Release

    - name: Install Moco
      run: |
        chdir $env:GITHUB_WORKSPACE\\build
        cmake --build . --config Release --target install -- /maxcpucount:4 /verbosity:quiet

        move ~/opensim-moco C:/opensim-moco-$env:VERSION
        7z a $env:GITHUB_WORKSPACE/opensim-moco.zip C:/opensim-moco-$env:VERSION

    # TODO: Fix name of the path to use tag/version.
    # Use {{ github.ref }}
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions
    - name: Upload Moco
      uses: actions/upload-artifact@v1.0.0
      with:
        name: opensim-moco
        path: opensim-moco.zip 

# TODO    - name: Upload Moco dependencies
# TODO      uses: actions/upload-artifact@v1.0.0
# TODO      with:
# TODO        name: opensim-moco-dependencies 
# TODO        path: C:\\opensim-moco-dependencies.zip
