name: continuous-integration-windows

# TODO: build master branch after PRs are merged.
# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on: pull_request
    
jobs:
  windows:
    name: Windows

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Chocolatey packages
      run: choco install swig --version 3.0.9 --yes --limit-output 

    - name: Install NumPy 
      run: python -m pip install numpy

    - name: Install Doxygen
      # choco install doxygen.portable # <-- too unreliable.
      run: |
        (New-Object System.Net.WebClient).DownloadFile("https://sourceforge.net/projects/myosin/files/doxygen-1.8.14.windows.x64.bin.zip/download", "C:\doxygen.zip")
        7z x C:\\doxygen.zip -oC:\\doxygen

    - name: Build dependencies
      # TODO: Add caching.
      run: |
        git submodule update --init
        echo %GITHUB_WORKSPACE%\\build_deps
        mkdir %GITHUB_WORKSPACE%\\build_deps
        chdir %GITHUB_WORKSPACE%\\build_deps
        cmake --version
        # /W0 disables warnings. The other flags are copied from CMake's
        # default CMAKE_CXX_FLAGS.
        # https://msdn.microsoft.com/en-us/library/19z1t1wy.aspx
        cmake %GITHUB_WORKSPACE%\\dependencies -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=%GITHUB_WORKSPACE%\\moco_dependencies_install -DCMAKE_CXX_FLAGS="/DWIN32 /D_WINDOWS /W0 /GR /EHsc"
        cmake . -LAH
        cmake --build . --config Release -- /maxcpucount:4 

    - name: Build Moco
      run: |
        mkdir %GITHUB_WORKSPACE%\\build 
        chdir %GITHUB_WORKSPACE%\\build
        # TODO: Can remove /WX when we use that in CMakeLists.txt.
        cmake -E env CXXFLAGS="/WX" cmake %GITHUB_WORKSPACE% -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=%GITHUB_WORKSPACE%\\opensim-core-install -DBUILD_PYTHON_WRAPPING=on -DBUILD_JAVA_WRAPPING=on -DDOXYGEN_EXECUTABLE=C:\\doxygen
        cmake . -LAH
        cmake --build . --config Release -- /maxcpucount:4 /verbosity:minimal

    - name: Test
      run: |
        chdir %GITHUB_WORKSPACE%\\build
        ctest --parallel 4 --output-on-failure --build-config Release

    - name: Install
      run: |
        chdir %GITHUB_WORKSPACE%\\build
        cmake --build . --config Release --target install -- /maxcpucount:4 /verbosity:quiet

    # TODO: Fix name of the path to use tag/version.
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: opensim-moco
        path: C:\\opensim-moco.zip

    - uses: actions/upload-artifact@v1.0.0
      with:
        name: opensim-moco-dependencies 
        path: C:\\opensim-moco-dependencies.zip
