name: Windows

# TODO: build master branch after PRs are merged.
# syntax https://help.github.com/en/articles/workflow-syntax-for-github-actions
on:
   pull_request:
     branches:
       - '*'
   push:
     tags:
       - '*'
    
jobs:
  windows:
    name: Windows

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Doxygen
      # choco install doxygen.portable # <-- too unreliable.
      run: |
        (New-Object System.Net.WebClient).DownloadFile("https://sourceforge.net/projects/myosin/files/doxygen-1.8.14.windows.x64.bin.zip/download", "doxygen.zip")
        7z x $env:GITHUB_WORKSPACE/doxygen.zip -odoxygen
        echo "::add-path::$env:GITHUB_WORKSPACE\\doxygen"

    - name: Install NumPy 
      run: python -m pip install numpy
 
    - name: Install SWIG
      run: choco install swig --version 3.0.12 --yes --limit-output 
 
    - name: Update submodules
      run: git submodule update --init

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v1
      with:
        path: ~/moco_dependencies_install
        # TODO: avoid having to copy over the opensim-core commit hash.
        key: ${{ runner.os }}-dependencies-${{ hashFiles('dependencies/*') }}
        restore-keys: |
          ${{ runner.os }}-dependencies-
 
    - name: Build dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        echo $env:GITHUB_WORKSPACE\\build_deps
        mkdir $env:GITHUB_WORKSPACE\\build_deps
        chdir $env:GITHUB_WORKSPACE\\build_deps
        # /W0 disables warnings. The other flags are copied from CMake's
        # default CMAKE_CXX_FLAGS.
        # https://msdn.microsoft.com/en-us/library/19z1t1wy.aspx
        $env:CXXFLAGS = "/W0"
        cmake $env:GITHUB_WORKSPACE/dependencies -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=~/moco_dependencies_install -DOPENSIM_JAVA_WRAPPING=on -DOPENSIM_PYTHON_WRAPPING=on
        $env:CXXFLAGS = ""
        cmake . -LAH
        cmake --build . --config Release -- /maxcpucount:4 

    - name: Configure Moco
      run: |
        mkdir $env:GITHUB_WORKSPACE\\build 
        chdir $env:GITHUB_WORKSPACE\\build        
        echo $env:PATH
        # TODO: Can remove /WX when we use that in CMakeLists.txt.
        $env:CXXFLAGS = "/WX"
        cmake $env:GITHUB_WORKSPACE -G"Visual Studio 16 2019" -A x64 -DCMAKE_INSTALL_PREFIX=~/opensim-moco -DMOCO_DEPENDENCIES_DIR=~/moco_dependencies_install -DMOCO_JAVA_BINDINGS=on -DMOCO_PYTHON_BINDINGS=on 
        $env:CXXFLAGS = ""
        cmake . -LAH
        $match = cmake -L . | Select-String -Pattern MOCO_FULL_VERSION
        $version = $match.split('=')[1]
        echo $version
        echo "::set-env name=VERSION::$version"

    - name: Build Moco
      run: |
        chdir $env:GITHUB_WORKSPACE\\build        
        cmake --build . --config Release -- /maxcpucount:4 /verbosity:minimal
        
    # TODO
    # - name: Test Moco
    #   run: |
    #     chdir $env:GITHUB_WORKSPACE\\build
    #     ctest --parallel 4 --output-on-failure --build-config Release

    - name: Install Moco
      run: |
        chdir $env:GITHUB_WORKSPACE\\build
        cmake --build . --config Release --target install -- /maxcpucount:4 /verbosity:quiet

        chdir $env:GITHUB_WORKSPACE
        move ~/opensim-moco opensim-moco-$env:VERSION

    # TODO: Fix name of the path to use tag/version.
    # Use {{ github.ref }}
    # https://help.github.com/en/actions/automating-your-workflow-with-github-actions/contexts-and-expression-syntax-for-github-actions
    - name: Upload Moco
      uses: actions/upload-artifact@v1.0.0
      with:
        name: opensim-moco
        path: opensim-moco-$env:VERSION

    # TODO: Must be relative to the workspace?
    # - name: Upload Moco dependencies
    #   uses: actions/upload-artifact@v1.0.0
    #   with:
    #     name: opensim-moco-dependencies 
    #     path: moco_dependencies_install.zip
