name: Mac

on: pull_request

jobs:
  mac:
    name: Mac

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Homebrew packages
      run: brew install cmake pkgconfig gcc autoconf libtool automake wget pcre doxygen

    - name: Cache SWIG
      id: cache-swig
      uses: actions/cache@v1
        with:
          path: ~/swig
          key: ${{ runner.os }}-swig

    - name: Install SWIG
      if: steps.cache-swig.outputs.cache-hit != 'true'
      run: |
        mkdir ~/swig-source && cd ~/swig-source
        wget https://github.com/swig/swig/archive/rel-3.0.12.tar.gz
        tar xzf rel-3.0.12.tar.gz && cd swig-rel-3.0.12
        sh autogen.sh && ./configure --prefix=$HOME/swig --disable-ccache
        make && make -j4 install

    - name: Update submodules
      run: git submodule update --init

    - name: Cache dependencies
      id: cache-dependencies
      uses: actions/cache@v1
        with:
          path: $GITHUB_WORKSPACE/moco_dependencies_install
          # TODO: avoid having to copy over the opensim-core commit hash.
          key: ${{ runner.os }}-dependencies-${{ hashFiles('dependencies/*') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
            
    - name: Build dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        mkdir $GITHUB_WORKSPACE/build_deps
        cd $GITHUB_WORKSPACE/build_deps
        DEP_CMAKE_ARGS=($GITHUB_WORKSPACE/dependencies)
        DEP_CMAKE_ARGS+=(-DCMAKE_BUILD_TYPE=Release)
        DEP_CMAKE_ARGS+=(-DOPENSIM_JAVA_WRAPPING=on -DOPENSIM_PYTHON_WRAPPING=on)
        DEP_CMAKE_ARGS+=(-DSWIG_EXECUTABLE=$HOME/swig/bin/swig)
        DEP_CMAKE_ARGS+=(-DCMAKE_OSX_DEPLOYMENT_TARGET=10.10)
        printf '%s\n' "${DEP_CMAKE_ARGS[@]}"
        cmake "${DEP_CMAKE_ARGS[@]}"
        make -j2 ipopt
        make -j2

    - name: Build Moco
      run: |
        mkdir $GITHUB_WORKSPACE/build
        cd $GITHUB_WORKSPACE/build
        MOCO_CMAKE_ARGS=($GITHUB_WORKSPACE)
        DEP_CMAKE_ARGS+=(-DCMAKE_BUILD_TYPE=Release)
        MOCO_CMAKE_ARGS+=(-DCMAKE_INSTALL_PREFIX=~/opensim-moco)
        MOCO_CMAKE_ARGS+=(-DMOCO_JAVA_BINDINGS=on -DMOCO_PYTHON_BINDINGS=on)
        MOCO_CMAKE_ARGS+=(-DSWIG_EXECUTABLE=$HOME/swig/bin/swig)
        MOCO_CMAKE_ARGS+=(-DCMAKE_OSX_DEPLOYMENT_TARGET=10.10)
        printf '%s\n' "${MOCO_CMAKE_ARGS[@]}"
        cmake "${MOCO_CMAKE_ARGS[@]}"
        cmake . -LAH
        VERSION=`cmake -L . | grep MOCO_FULL_VERSION | cut -d "=" -f2`
        echo $VERSION
        make -j2

    - name: Test Moco
      run: |
        ctest -j2 --output-on-failure

    - name: Install Moco
      run: |
        make Moco_doxygen
        make -j2 install

    - name: Zip Moco
      run: |
        mkdir ~/to_upload
        ZIPNAME=opensim-moco-${VERSION}-mac.zip
        # Zip up Moco relative to where it's installed.
        cd ~/
        mv ~/opensim-moco ~/opensim-moco-${VERSION}
        zip --symlinks --recurse-paths --quiet ~/to_upload/$ZIPNAME opensim-moco-${VERSION}

    - name: Upload Moco
      uses: actions/upload-artifact@v1.0.0
      with:
        name: opensim-moco
        path: ~/to_upload/$ZIPNAME

 

        
