name: continuous-integration-mac

on: pull_request

jobs:
  mac:
    name: Mac

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Homebrew packages
    - run: brew install openblas doxygen

    - name: Install SWIG
    - run: |
        mkdir ~/swig-source && cd ~/swig-source
        wget https://github.com/swig/swig/archive/rel-3.0.9.tar.tz
        tar xzf rel-3.0.9.tar.gz && cd swig-rel-3.0.9
        sh autogen.sh && ./configure --prefix=$HOME/swig --disable-ccache
        make && make -j4 install

